[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solstage_program = "STAGYb3HZJW8CV1QEbhyc8WkLuJt44RtWHDpRgHe2pX"

[programs.mainnet]
solstage_program = "STAGYb3HZJW8CV1QEbhyc8WkLuJt44RtWHDpRgHe2pX"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
